def configure(conf):
    conf.load('xwaf.compiler_xcc')


def build(bld):
    bld.env.TARGET_ARCH = 'src/xk-audio-216-mc.xn'
    bld.env.XCC_FLAGS = [
        '-Wall', '-g', '-O2', '-report', '-save-temps',
        '-DXUD_SERIES_SUPPORT=4', '-DUSB_TILE=tile[1]', '-report'
    ]

    source = bld.path.ant_glob('src/*.xc')

    # Build our program
    prog = bld.program(
        source=source,
        depends_on='lib_device_control lib_usb')


# TARGET = xk-audio-216-mc
# XCC_FLAGS = -Wall -g -O2 -report -save-temps -DXUD_SERIES_SUPPORT=4 -DUSB_TILE=tile[1] -report
# USED_MODULES = lib_device_control lib_usb
# XMOS_MAKE_PATH ?= ../..
# include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
