# This file relates to internal XMOS infrastructure and should be ignored by external users
---
lib_name: lib_device_control
project: '{{lib_name}}'
title: '{{lib_name}}: Device Control for xcore'
version: 5.0.0

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  root_doc: doc/rst/lib_device_control.rst
  linkcheck_ignore_regex: ['']
  latex_toc_depth: 3
  latex_secnum_depth: 3
  cognidox_part_number: XM-010892-UG
  doxygen_projects:
    lib_device_control:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/lib_device_control.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
software:
  cognidox_part_number: XM-010580-SM
