ROOT = ../../../..


all:
	mkdir -p bin
	cd src ; gcc -Wall -g -D HOST_APP -o ../bin/xscope.out -I $(ROOT)/lib_device_control/api -I $(ROOT)/lib_device_control/src -I $(ROOT)/lib_device_control/host -I $(ROOT)/lib_device_control/host -I ${XMOS_TOOL_PATH}/include ${XMOS_TOOL_PATH}/lib/xscope_endpoint.so -D USE_XSCOPE $(ROOT)/lib_device_control/host/device_access_xscope.c $(ROOT)/lib_device_control/host/util.c host.c

clean:
	rm -rf bin
