TARGET = mic_array_ref.xn
XCC_FLAGS = -fxscope -Wall -g
USED_MODULES = lib_device_control lib_i2c lib_logging
XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
