TARGET = MIC-ARRAY-1V0.xn
XCC_FLAGS = -fxscope -Wall -g -O2 -report
#XCC_FLAGS += -D ERRONEOUS_DEVICE
USED_MODULES = lib_device_control lib_mic_array_board_support
XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
