TARGET = mic_array_ref.xn
XCC_FLAGS = -fxscope -Wall -g
#XCC_FLAGS += -D ERRONEOUS_DEVICE
USED_MODULES = lib_device_control
XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
