ROOT = ../../../..

all:
	mkdir -p bin
	cd src ; gcc -Wall -g  -D USE_USB  -I ../libusb/Linux32 -o ../bin/usb_host_app.out -I $(ROOT)/lib_device_control/api -I $(ROOT)/lib_device_control/src -I $(ROOT)/lib_device_control/host $(ROOT)/lib_device_control/host/device_access_usb.c $(ROOT)/lib_device_control/host/util.c host.c -lusb-1.0

clean:
	rm -rf bin
