TARGET = XK_VOICE_L71.xn
XCC_FLAGS = -fxscope -Wall -g -O2 -report
#XCC_FLAGS += -D ERRONEOUS_DEVICE
USED_MODULES = lib_device_control
XMOS_MAKE_PATH ?= ../..
# Ignore host dir
SOURCE_DIRS = src
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
