TARGET = MIC-ARRAY-1V0.xn
XCC_FLAGS = -fxscope -Wall -g -O2 -report
USED_MODULES = lib_device_control lib_i2c lib_logging lib_mic_array_board_support
XMOS_MAKE_PATH ?= ../..
EXCLUDE_FILES = host_xcore/src/host.xc
EXCLUDE_DIRS = 
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
