def configure(conf):
    conf.load('xwaf.compiler_xcc')


def build(bld):
    bld.env.TARGET_ARCH = 'XCORE-200-EXPLORER'
    bld.env.XCC_FLAGS = ['-g', '-O2']

    source = bld.path.ant_glob('src/*.xc')

    # Build our program
    prog = bld.program(
        source=source,
        depends_on='lib_device_control')
