TARGET = XCORE-200-EXPLORER
XCC_FLAGS = -Wall -g -O2 -report -DUSE_I2C=1 -save-temps
USED_MODULES = lib_device_control lib_i2c
XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
