ROOT = ../../..

all:
	mkdir -p bin
	cd src ; gcc -Wall -g -I $(ROOT)/lib_device_control/host/examples/usb/libusb/OSX64 -o ../bin/usb_end_to_end_hardware_host.out -I $(ROOT)/lib_device_control/api -I $(ROOT)/lib_device_control/src -I $(ROOT)/lib_device_control/host/api -I $(ROOT)/lib_device_control/host/host_src $(ROOT)/lib_device_control/host/examples/usb/libusb/OSX64/libusb-1.0.0.dylib -D USE_USB $(ROOT)/lib_device_control/host/host_src/device_access_usb.c $(ROOT)/lib_device_control/host/host_src/util.c host.c signals.c

clean:
	rm -rf bin
