def configure(conf):
    conf.load('xwaf.compiler_xcc')


def build(bld):
    bld.env.TARGET_ARCH = 'XCORE-200-EXPLORER'
    bld.env.XCC_FLAGS = ['-g']

    # Build our program
    prog = bld.program(
        source='src/test.xc',
        depends_on='lib_device_control')

# TARGET = XCORE-200-EXPLORER
# USED_MODULES = lib_device_control
# XCC_FLAGS = -g
# XMOS_MAKE_PATH ?= ../..
# -include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
