all:
	mkdir -p bin
	cd src ; gcc -Wall -g -o ../bin/a.out -I ../../../../lib_device_control/api -I ${XMOS_TOOL_PATH}/include ${XMOS_TOOL_PATH}/lib/xscope_endpoint.so signals.c util.c host.c

clean:
	rm -rf bin
