all:
	mkdir -p bin
	cd src ; gcc -Wall -g -o ../bin/a.out -I ../../../lib_device_control/api -I ../../../lib_device_control/src -I ../../../lib_device_control/host -I ${XMOS_TOOL_PATH}/include ${XMOS_TOOL_PATH}/lib/xscope_endpoint.so -D USE_XSCOPE ../../../lib_device_control/host/device_access_xscope.c ../../../lib_device_control/host/util.c signals.c host.c

clean:
	rm -rf bin
