TARGET = XCORE-200-EXPLORER
USED_MODULES = lib_device_control
XCC_FLAGS = -g -O2 -DUSE_I2C=1 -DUSE_USB=1 -DUSE_XSCOPE=1
XMOS_MAKE_PATH ?= ../..
-include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
